version: '3.8'

services:
  app:
    build:
      dockerfile: app.Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - database
  postgres-db:
    build:
      dockerfile: database.Dockerfile
      context: ./database
    ports:
      - "8081:5432"
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres'"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - database
networks:
  database:
    driver: bridge